services:

    commons_search_tab:
        class: Ibexa\Platform\Connector\Dam\View\Search\Tab\GenericSearchTab
        public: false
        arguments:
            $twig: '@twig'
            $translator: '@translator'
            $identifier: 'commons'
            $source: 'commons'
            $name: 'Wikimedia Commons'
            $searchFormType: 'Ibexa\Platform\Connector\Dam\Form\Search\GenericSearchType'
            $formFactory: '@form.factory'
            $configResolver: '@ezpublish.config.resolver'
        tags:
            - { name: ezplatform.tab, group: connector-dam-search }

    AdrienDupuis\EzPlatformConnectorCommonsBundle\Handler\Handler:
        tags:
            - { name: ibexa.platform.connector.dam.handler, source: commons }

    AdrienDupuis\EzPlatformConnectorCommonsBundle\Variation\TransformationFactory:
        tags:
            - { name: ibexa.platform.connector.dam.transformation_factory, source: commons }

    commons_asset_variation_generator:
        class: Ibexa\Platform\Connector\Dam\Variation\URLBasedVariationGenerator
        tags:
            - { name: ibexa.platform.connector.dam.variation_generator, source: commons }
